[package]
name = "switch-usb-controld"
version = "0.1.0"
edition = "2021"

[dependencies]
nusb = "0.1.11"
futures-lite = "2.5.0"
gilrs = "0.11.0"
bidirectional-map = "0.1.4"
lazy_static = "1.5.0"
inquire = "0.7.5"